name: TestDriver.ai Regression Testing - Waveterm
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 21 * * *
  workflow_dispatch: null

permissions:
  contents: read # To allow the action to read repository contents
  pull-requests: write # To allow the action to create/update pull request comments

jobs:
  test:
    name: "TestDriver"
    runs-on: ubuntu-latest
    steps:
      - uses: testdriverai/action@main
        id: testdriver
        with:
          key: ${{secrets.DASHCAM_API}}
          prerun: |
            # Set variables
            $msys2Url = "https://www.msys2.org/"
            $goUrl = "https://go.dev/dl/"

            # Function to open a URL for manual installations
            function Open-Url {
                param (
                    [string]$url
                )
                Start-Process $url
            }

            # Install MSYS2 (GNU build toolchain)
            Write-Host "Please install MSYS2 for the GNU build toolchain from the following URL:"
            Open-Url -url $msys2Url
            Pause

            # Install Go
            Write-Host "Please download and install Go from the following URL:"
            Open-Url -url $goUrl
            Pause

            # Enable Corepack for Yarn Modern (assuming NodeJS is already installed)
            Write-Host "Enabling Corepack for Yarn Modern..."
            npm install -g corepack
            corepack enable

            # Navigate into the existing repository folder (replace this with the correct path)
            $repoPath = "C:\path\to\waveterm"  # <-- Replace with your actual repository path
            Set-Location $repoPath

            # Perform a standalone build
            Write-Host "Building and running standalone..."
            task electron:start

            Write-Host "
          prompt: |
            1. /run testdriver/theme.yml
